AWSTemplateFormatVersion: 2010-09-09
Description: Deploy Profile

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Profile Configuration"
        Parameters:
          - s3Bucket
          - ec2Instances

    ParameterLabels:
      s3Bucket:
        default: "Input S3 Bucket for Backups"
      ec2Instances:
        default: "Input a comma-separated list of EC2 Instances to receive the Instance Profile"

Parameters:
  s3Bucket:
    Type: String
    Default: snaps.example.com
  ec2Instances:
    Type: CommaDelimitedList
    Default: i-123456789,i-234567890,i-345678901

Resources:
  Ec2ProfileRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
  RolePolicies:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "ec2profilepolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "s3:ListBucket"
              - "s3:GetBucketLocation"
              - "s3:ListBucketMultipartUploads"
              - "s3:ListBucketVersions"
            Resource: !Join ['', ["arn:aws:s3:::", !Ref s3Bucket ]]
          -
            Effect: "Allow"
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
              - "s3:AbortMultipartUpload"
              - "s3:ListMultipartUploadParts"
            Resource: !Join ['', ["arn:aws:s3:::", !Ref s3Bucket, "/*" ]]
      Roles:
        -
          Ref: "Ec2ProfileRole"
  Ec2InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        -
          Ref: "Ec2ProfileRole"
