AWSTemplateFormatVersion: 2010-09-09
Description: Deploy ECE IAM Resources for Networking Tier

Resources:
  FlowLogRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "vpc-flow-logs.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
  RolePolicies:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "flowlogpolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:DescribeLogGroups"
              - "logs:DescribeLogStreams"
              - "logs:PutLogEvents"
            Resource: "*"
      Roles:
        -
          Ref: "FlowLogRole"

Outputs:
  FlowLogRole:
    Description: FlowLog Role CrossStack ID
    Value: !GetAtt FlowLogRole.Arn
    Export:
      Name:
        !Sub "${AWS::StackName}-FlowLogRole"