AWSTemplateFormatVersion: 2010-09-09
Description: Configure the Cross-Account IAM Member Account Roles for EC2 Shutdown and Startup

Parameters:
  ManagedResourcePrefix:
    Type: 'String'
    Description: 'Prefix for the managed resources'
    Default: 'EC2Automation'
  CrossAccountRole:
    Type: 'String'
    Description: 'Cross Account Role Deployed into Master Account'
    Default: 'arn:aws:iam::XXXXXXXXXXXX:role/EC2Automation-AdminRole'
Resources:
  EC2ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ManagedResourcePrefix}-ExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref CrossAccountRole
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub ${ManagedResourcePrefix}-ExecutionRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:DescribeInstances"
                  - "ec2:StopInstances"
                  - "ec2:StartInstances"
                  - "ec2:DescribeInstanceStatus"
                Resource: "*"
